# Generated by Django 5.2.10 on 2026-02-27 23:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fqid', models.URLField(unique=True)),
                ('author_fqid', models.URLField()),
                ('entry_fqid', models.URLField()),
                ('comment', models.TextField()),
                ('content_type', models.CharField(max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fqid', models.URLField(unique=True)),
                ('author_fqid', models.URLField()),
                ('object_fqid', models.URLField()),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
