"""Database migration 0001_initial for social."""

# Generated by Django 5.2.10 on 2026-02-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_fqid', models.URLField()),
                ('following_fqid', models.URLField()),
                ('accepted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('follower_fqid', 'following_fqid')},
            },
        ),
    ]
