"""Database migration 0002_remoteauthor for nodes."""

# Generated by Django 5.2.10 on 2026-03-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqid', models.URLField(unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('host', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('profile_image', models.URLField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_authors', to='nodes.node')),
            ],
            options={
                'ordering': ['display_name', 'fqid'],
            },
        ),
    ]
