"""Database migration 0005_alter_node_base_url for nodes."""

# Generated by Django 5.2.10 on 2026-03-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_node_sync_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='base_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
