# Generated by Django 4.2.28 on 2026-03-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='description',
        ),
    ]
