"""Database migration 0004_author_description for authors."""

# Generated by Django 5.2.10 on 2026-03-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_remove_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
